### ISSUE TITLE
Looking for an AUR package maintainer

### ISSUE THREAD

**Issue by dominiksalvet** [dominiksalvet/asus-fan-control#11]
Hello @agura-lex!

I am creating this issue in connection with #10 (and [this comment](https://github.com/dominiksalvet/asus-fan-control/pull/10#issuecomment-568570610)) to keep the PR itself clearer as it started to be exhaustive. I would rather email this to you but I couldn't find your email address.

I will try to make new updates not to be very invasive and hence easy or with zero effort to update [the AUR package](https://aur.archlinux.org/packages/asus-fan-control/). It would be great if you could update the AUR package once a while but I do not want to limit you somehow. So it is completely up to you.

Nevertheless, I would be very happy if can you join this project as a collaborator. You have added the systemd support to asus-fan-control (#10) and have created the AUR package (#9) for dear Arch users. It would be great if you can participate in the slow-paced development of this project and help me with systemd and AUR package maintenance as I do not understand them very well and you are the AUR package's maintainer anyway... :smile: 

If you are in, we can add the AUR installation method to *README.md* file for people to know and I won't be scared of AUR package-related issues from users.

What do you think? Are you interested? :rocket:

**Comment by agura-lex** [comment]
Hello and Merry Christmas! 

Well, of course I'm ready to take the burden of maintaining the AUR package, that was the idea when I decided to create it! I'm already subscribed to new releases by email, so shouldn't miss 'em. And I also thought about adding AUR installation guide to the README, just didn't feel it's necessary because I assumed that Arch users are usually familiar with AUR and they search third-party stuff there, but now when I think about it, I feel less confident about that lol, so adding that is certainly welcome! I can make a pull request with everything needed.  

If you have any questions about any of that stuff, feel free to ask!

**Comment by dominiksalvet** [comment]
Glad to hear that! :smile: I have sent you a collaborator invitation. :rocket: 

If you have time and you want to, you can create the PR. Otherwise, I would do it myself a bit later... :smile:

I think I do not have any questions right now. Feel free to close this issue after accepting the invitation.

**Comment by dominiksalvet** [comment]
It would be also great to add you as the code owner of *asus-fan-control.service* file to automatize possible future PRs. Just a note for me to do it later... :smile:
