### ISSUE TITLE
Installation script assumes systemd

### ISSUE THREAD

**Issue by LoganDark** [dominiksalvet/asus-fan-control#115]
**Environment**
AFC commit `2831af8bf6da841b8f2bdbc9b93e02d0d91ca5a0`, AntiX Linux 21, ROG Zephyrus M15 (i7-10750)

**Description**
Installation script (run by gitpack) assumes systemd

**Replication**
Install `asus-fan-control` on a system without `systemd`, it will try to install service files and use `systemctl`.

Luckily it still succeeds despite this.

**Additional context**
N/A

**Comment by LoganDark** [comment]
> AFC does not require systemd to work

Aware :)

> What is your expected behavior or solution?

Just check for the existence of systemctl before trying to use it. Print a notice if it's not found.

**Comment by dominiksalvet** [comment]
Are you able to prepare a PR on this?

**Comment by LoganDark** [comment]
> Are you able to prepare a PR on this?

Sorry, I completely missed this comment-- I tinker with Linux every now and then but I quickly run out of energy to deal with it because it's always really annoying. I guess you just reached me at a time when my energy was depleted. :(

Maybe one day

**Comment by dominiksalvet** [comment]
It is okay. I have also changed my mind about this issue since the behavior is appropriate. The systemd service does not only care about running AFC but it also cares about loading the ACPI module... However, I will not let the installation script fail when systemd is not present so people can still install AFC using GitPack.
