### ISSUE TITLE
acpi call failed with 'Error: AE_NOT_FOUND'

### ISSUE THREAD

**Issue by Chris56** [dominiksalvet/asus-fan-control#125]
**Environment**
Lastest gitpack install
Linux mint 20.3
Kernel: 5.4.0-128-generic #144-Ubuntu SMP Tue Sep 20 11:00:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
System Board: product: X541SA (ASUS-NotebookSKU)
CPU:
   *-cpu
          description: CPU
          product: Intel(R) Celeron(R) CPU  N3060  @ 1.60GHz
          vendor: Intel Corp.
          physical id: 13
          bus info: cpu@0
          version: Intel(R) Celeron(R) CPU N3060 @ 1.60GHz
          slot: SOCKET 0
          size: 708MHz
          capacity: 2480MHz
          width: 64 bits
          clock: 80MHz

sensors:
asus-isa-0000
Adapter: ISA adapter
cpu_fan:     2300 RPM
temp1:       +6280.0°C  

soc_dts0-virtual-0
Adapter: Virtual device
temp1:        +32.0°C  

BAT0-acpi-0
Adapter: ACPI interface
in0:          10.80 V  

soc_dts1-virtual-0
Adapter: Virtual device
temp1:        +31.0°C  

coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +37.0°C  (high = +90.0°C, crit = +90.0°C)
Core 2:       +36.0°C  (high = +90.0°C, crit = +90.0°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +35.0°C  (crit = +95.0°C)
temp2:        +35.0°C  (crit = +94.0°C)

Note the 
temp1:       +6280.0°C  

**Description**
Calling aus-fan-control leads to
acpi call failed with 'Error: AE_NOT_FOUND', fan is always running
However:
When I suspend to ram and rewake up the machine, the fan is off and even does not start running under load!
I gues the coretemp temperature are correct, they do go up under load. However no fan (once it had been suspended once.
All very strange!

Cheers
Chris

**Comment by dominiksalvet** [comment]
Hello, since AFC ended up with AE_NOT_FOUND, I suspect it has no impact on the device behavior. Unfortunately, this issue has not been solved yet, if even possible...

**Comment by dominiksalvet** [comment]
I understand your point of view but look at other issues labeled AE_NOT_FOUND (and similar). It is not possible to keep them all open and tracked. The fact is that AFC will not ever run on some devices. Furthermore, it is not here to run on any ASUS device, I just shared my work with others.

I try to keep all issues open as long as possible so that other people may add comments, recommendations, links for alternative SW, etc. But I am not willing to keep issues without any activity open forever.

I believe you can still find this issue on search engines as well as you can add comments. Should something significant change, I would reopen it. But as this issue stands, it is solved for me from the point of an AFC developer (there is nothing I can do).
