### ISSUE TITLE
Add support for Asus zenbook duo UX482

### ISSUE THREAD

**Issue by IgnIVertiKalCaD** [dominiksalvet/asus-fan-control#141]
**Environment**
asus-fan-control 3.13.0

OS version="Archlinux | kernel 6.4.5"
CPU: quad core 11th Gen Intel Core i5-1135G7 (-MT MCP-)

**It does not work**
sudo asus-fan-control get-temps
acpi call failed with 'Error: AE_NOT_FOUND'

**Additional context**
An error pops up. I have seen it with other users, but I have not been able to solve it. Maybe it's about the support of the utility?

**Comment by dominiksalvet** [comment]
It seems newer CPUs are related hardware are not supported...

**Comment by IgnIVertiKalCaD** [comment]
Not so terrible then, since I can directly set fan RPM with sudo echo 0 > /sys/devices/platform/asus-nb-wmi/hwmon/hwmon4/pwm1_enable. 
But there is a problem that, hwmon changes, after every reboot of the laptop and I don't know how to fix it. Do you have any ideas. Thank you very much in advance

**Comment by IgnIVertiKalCaD** [comment]
```
#!/bin/bash
# my English is very bad, sorry me
#Asus zenbook duo UX482 bios 318

#  0 - full speed
#  2 - auto / silent. I dont know
#  1 - dont working. Why? I dont know XD

set_fan_speed() {
    local speed=$2
    echo "$speed" > "$1"
}

hwmon_number=""
for entry in /sys/devices/platform/asus-nb-wmi/hwmon/hwmon[0-9]*/; do
    hwmon_number="${entry%/}"
done

if [[ -n "$hwmon_number" ]]; then
    hwmon_number="${hwmon_number##*hwmon}"
    
    full_path_to_real_hwmon="/sys/devices/platform/asus-nb-wmi/hwmon/hwmon${hwmon_number}/pwm1_enable"
    sudo chmod -R 777 $full_path_to_real_hwmon
    
    read -r mode_fans < $full_path_to_real_hwmon

    if [ "$mode_fans" -eq 2 ]; then
        set_fan_speed "$full_path_to_real_hwmon" 0
    else
        set_fan_speed "$full_path_to_real_hwmon" 2
    fi

else
    echo "Nothing found."
fi

```

I wrote a script like this that works on my laptop. Maybe someone will need...

**Comment by ezaron** [comment]
I receive the same AE_NOT_FOUND error on my desktop ASUS PA90.

Running ubuntu linux 23.04 (GNU/Linux 5.19.0-23-generic x86_64)

My fan runs loud/high since upgrade to 23.04.

sensors-detect returns these:
Driver `coretemp':
  * Chip `Intel digital thermal sensor' (confidence: 9)
Driver `nct6775':
  * ISA bus, address 0x290
    Chip `Nuvoton NCT6796D Super IO Sensors' (confidence: 9)

And sensors give this:
~$ sensors
nouveau-pci-0100
Adapter: PCI adapter
fan1:        3472 RPM
temp1:        +51.0°C  (high = +95.0°C, hyst =  +3.0°C)
                       (crit = +105.0°C, hyst =  +5.0°C)
                       (emerg = +135.0°C, hyst =  +5.0°C)

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +37.0°C  (high = +86.0°C, crit = +100.0°C)
Core 0:        +36.0°C  (high = +86.0°C, crit = +100.0°C)
Core 1:        +37.0°C  (high = +86.0°C, crit = +100.0°C)
Core 2:        +35.0°C  (high = +86.0°C, crit = +100.0°C)
Core 3:        +35.0°C  (high = +86.0°C, crit = +100.0°C)
Core 4:        +35.0°C  (high = +86.0°C, crit = +100.0°C)
Core 5:        +34.0°C  (high = +86.0°C, crit = +100.0°C)
Core 6:        +36.0°C  (high = +86.0°C, crit = +100.0°C)
Core 7:        +35.0°C  (high = +86.0°C, crit = +100.0°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +44.0°C  (crit = +100.0°C)

iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +36.0°C  

pch_cannonlake-virtual-0
Adapter: Virtual device
temp1:        +51.0°C  

nvme-pci-0200
Adapter: PCI adapter
Composite:    +33.9°C  (low  = -273.1°C, high = +80.8°C)
                       (crit = +81.8°C)
Sensor 1:     +33.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +35.9°C  (low  = -273.1°C, high = +65261.8°C)

And fancontrol says this:
fancontrol
Loading configuration from /etc/fancontrol ...
Some mandatory settings missing, please check your config file!

**Comment by dominiksalvet** [comment]
> Not so terrible then, since I can directly set fan RPM with `sudo echo 0 > /sys/devices/platform/asus-nb-wmi/hwmon/hwmon4/pwm1_enable. ` But there is a problem that, **hwmon** changes, after every reboot of the laptop and I don't know how to fix it. Do you have any ideas? Thank you very much in advance

Maybe you can use a similar approach to AFC's. Have a look at the installation script https://github.com/dominiksalvet/asus-fan-control/blob/master/.install/install-global-Linux and focus on afc.service file. That could be helpful.
