### ISSUE TITLE
Active status systemCTL

### ISSUE THREAD

**Issue by nigelwarning** [dominiksalvet/asus-fan-control#22]
This is probably a noob question! But I justed wanted to know for sure.

● asus-fan-control.service - Fan control for ASUS devices running Linux.
   Loaded: loaded (/usr/lib/systemd/system/asus-fan-control.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Fri 2020-02-28 01:44:20 CET; 11min ago
  Process: 789 ExecStartPre=/sbin/modprobe acpi_call (code=exited, status=0/SUCCESS)
  Process: 799 ExecStart=/usr/bin/asus-fan-control (code=exited, status=0/SUCCESS)
 Main PID: 799 (code=exited, status=0/SUCCESS)

feb 28 01:44:20 Manjaro systemd[1]: Starting Fan control for ASUS devices running Linux....
feb 28 01:44:20 Manjaro systemd[1]: asus-fan-control.service: Succeeded.
feb 28 01:44:20 Manjaro systemd[1]: Started Fan control for ASUS devices running Linux..

Its says loaded, but active: inactive (dead)
Is this right? The fans are under 55 degrees, but would it be active when its goes up? I use the defaults temps!

**Comment by dominiksalvet** [comment]
Hello @nigelwarning and welcome to the asus-fan-control community! :wave:

First, no question is a noob question - not all people have the same knowledge and I respect it. :+1: Even I personally do not know the answer, which I can be 100% sure with, so please @agura-lex check my answer below whether it is right.

It is good to know that asus-fan-control is not a daemon. So it does not control fan speed actively, rather it uses the ACPI interface and sets temperatures values at critical points (boot, wake from hibernate, etc.) to keep the effect of a permanent change. Those critical points usually reset the ACPI values to their vendor-default values, so that is the reason they are important for us.

Once those values are set, the mechanism on the other side of ACPI (firmware + hardware) will handle all fan speed controlling. If you are interested in the implementation of our systemd service, take a look at the [*asus-fan-control.service*](https://github.com/dominiksalvet/asus-fan-control/blob/master/.gitpack/data/asus-fan-control.service) file.

So **the answer to your first question** is yes, it is correct behavior. :+1: 

To **answer your second question**, I need a little information about your laptop model. Please, what is the output of `sudo asus-fan-control model-info`?

---

BTW, you could have created this issue from the question template, we actually have it - take a look at the last issue template [here](https://github.com/dominiksalvet/asus-fan-control/issues/new/choose).

**Comment by nigelwarning** [comment]
`name VivoBookS15X530UA
address 1335
temperatures '55 60 62 65 68 72 76 80'
tested false
`

This do I get as output. I changed the values to 55 57 59 61 63 65 67 69 becuase the other Vivobooks used it too. But tried some other values and indeed when I did a lower value it started spinning earlier then now. But I love it. By default without this script my Asus fans would spin like everytime, now only when its needed.

What is by the way the best acpi_call to install? I got to choose between multiple version. I installed the linux54-acpi_call because I am running kernel 5.4. But is there a better option for it?

**Comment by dominiksalvet** [comment]
@nigelwarning Well, your device is not added as tested yet. Please, add it as described in the [CONTRIBUTING.md](https://github.com/dominiksalvet/asus-fan-control/blob/master/CONTRIBUTING.md) file and then the **answer to your second original question** will be yes! :rocket:

> What is by the way the best acpi_call to install? I got to choose between multiple version. I installed the linux54-acpi_call because I am running kernel 5.4. But is there a better option for it? I am using Manjaro stable by the way :)

This is a question rather for @agura-lex - please take a look at it once you have time. Thanks. :heart:

**Comment by agura-lex** [comment]
>What is by the way the best acpi_call to install? I got to choose between multiple version. I installed the linux54-acpi_call because I am running kernel 5.4.

You installed the correct one. :)

>Its says loaded, but active: inactive (dead)

Systemd loads all units from /run/systemd/system, /etc/systemd/system and /lib/systemd/system, so that's totally normal. And, as @dominiksalvet pointed out, it's not an active daemon, it just talks to ACPI once to supply temperatures table.

**Comment by agura-lex** [comment]
We could add `RemainAfterExit=true`, so it would display as active once it's run, but since you can't "stop" it, there's no point in that, as for me.

**Comment by dominiksalvet** [comment]
> We could add `RemainAfterExit=true`, so it would display as active once it's run, but since you can't "stop" it, there's no point in that, as for me.

I agree. :smile:

Closing this issue as solved. Please, @nigelwarning do not forget to add your laptop model as said previously.

**Comment by dominiksalvet** [comment]
Hey @nigelwarning, how is your laptop doing with asus-fan-control? I would gladly add your device as tested but I can't without your confirmation...

Once you have time, please consider adding it to asus-fan-control officially - for that, open a [new issue](https://github.com/dominiksalvet/asus-fan-control/issues/new/choose) and fill out the Basic configuration section... it is that easy! :smile: And it can help other people with the same device. :rocket:

**Comment by nigelwarning** [comment]
Ive been using the 55 57 59 61 63 65 67 69 values. But only because the other VIVO books are using it too. When watching a Youtube video the temp go to around 48-55 degrees celcius, while on Windows it is around 38 celcius. So I dont know how reliable the values really are.

**Comment by dominiksalvet** [comment]
@nigelwarning Great to see you again! Please, are you able to create [a new issue](https://github.com/dominiksalvet/asus-fan-control/issues/new/choose) on that? Or at least write something to #29? That would make the whole thing clearer. :smile: :rocket:
