### ISSUE TITLE
Looking for an ASUS VivoBook S15 S530UA tester

### ISSUE THREAD

**Issue by dominiksalvet** [dominiksalvet/asus-fan-control#29]
Hello open source contributors! :wave:

Asus-fan-control may be able to extend the tested devices list! If you come to **have an ASUS VivoBook S15 S530UA** (X530UA) laptop, please **let us know**! :rocket: 

We were waiting for @nigelwarning to add this device (#22) as it looks that this user has that laptop up and running with asus-fan-control. That means there should be no problems at all with running asus-fan-control on the mentioned device!

Have a wonderful day guys! :smile:

**Comment by nigelwarning** [comment]
Using and testing this right now.

After using the command `sudo asus-fan-control model-info` for the first time i got the next results:

`name VivoBookS15X530UA
address 1335
temperatures 55 60 62 65 68 72 76 80
tested false`

I changed the values to:
`55 57 59 61 63 65 67 69`

Because the other 2 Vivobooks has the same values too.

The only problem I really have is the difference in temperature in Windows and in Manjaro Linux.
In Windows the temps are between 30 - 40 degrees celcius, most of the time around 33. When watching a Youtube 1080p video this will maybe rise 2/3 degrees celcius, but nothing more.

On Linux my temps raise from 40 idle ( In KDE ) I notice in XFCE this is lower, to around 50-53 degrees celcius when playing a Youtube 1080p video. This is maybe more of a Linux problem then a asus-fan-control problem. But thats the only thing where Windows does a better job then Linux for me.

**Comment by dominiksalvet** [comment]
@nigelwarning BTW what is the real full name of your laptop, please? I mean what is written e.g. on the box, not the dmidecode or asus-fan-control output...

**Comment by nigelwarning** [comment]
https://www.asus.com/us/Laptops/ASUS-VivoBook-S15-S530UA/Tech-Specs/

https://www.amazon.com/VivoBook-Portable-i5-8250U-Processor-S530UA-DB51-YL/dp/B07DKW9NSL

Its this one :)

**Comment by dominiksalvet** [comment]
@nigelwarning Ok, thank you so much for all provided information! :heart: I will try to add support for your model as soon as possible. Once I do, I will close this issue and then you can just use `sudo gitpack install github.com/dominiksalvet/asus-fan-control` to update. :rocket: 

---

As far as I can remember, I have also observed ineffective hardware usage during playing videos in web browsers on Linux compared to Windows 10. As you have said, this does not look like a problem with asus-fan-control itself, rather I think that it is caused by graphics drivers, hardware acceleration, or rendering.

**Comment by dominiksalvet** [comment]
@nigelwarning Thank you for the contribution! :heart: The new version is out! :rocket:
