### ISSUE TITLE
can this work in ASUS TUF FX505DY ?

### ISSUE THREAD

**Issue by AnasR7** [dominiksalvet/asus-fan-control#35]
Can this is asus-fan-control work in my Laptop ASUS TUF FX505DY

Thanks.

**Comment by dominiksalvet** [comment]
Welcome to the asus-fan-control community! :wave:

I knew this question is going to be asked. Unfortunately, ASUS laptops are like a box of chocolates in this regards - you never know what you're gonna get. Hence the list of tested laptops so that people know what to expect. :smile: 

In case of a new laptop, like yours, I can't say whether it will work, or not until someone actually tries it. If you worry about doing that, you might want to first look at the ACPI table whether there are signs of temperature values, which should be less invasive. I have created [afc-scout](https://github.com/dominiksalvet/afc-scout) for this purpose. I would suggest to start with addresses stated in [Example](https://github.com/dominiksalvet/afc-scout#example) - 1334, 1343.

Feel free to try it and let me know.

**Comment by AnasR7** [comment]
When I use, sudo afc-scout 
there's no model address detected just get zero in every run.

```
[4078] = 0
[4079] = 0
[4080] = 0
[4081] = 0
[4082] = 0
[4083] = 0
[4084] = 0
[4085] = 0
[4086] = 0
[4087] = 0
[4088] = 0
[4089] = 0
[4090] = 0
[4091] = 0
[4092] = 0
[4093] = 0
[4094] = 0
[4095] = 0
```

**Comment by dominiksalvet** [comment]
> I would suggest to start with addresses stated in [Example](https://github.com/dominiksalvet/afc-scout/blob/master/readme.md#example) - 1334, 1343.

What is the output for `sudo afc-scout 1334 1343`?
