### ISSUE TITLE
Add support for VivoBook Pro 15 X580VD

### ISSUE THREAD

**Issue by AntonisKl** [dominiksalvet/asus-fan-control#38]
#### Environment
**OS**: Ubuntu 19.10
**asus-fan-control version**: 3.6.0

#### Basic configuration
```
sudo asus-fan-control get-temps
45 50 55 60 65 70 75 80
```
```
sudo asus-fan-control model-info
name X580VD
address 1335
temperatures 45 50 55 60 65 70 75 80
tested false
```

#### Additional context
Firstly, thank you for this tool because after a lot of searching, it was the only one to be working with this laptop.
I have a note to make for this laptop:
This model has 2 fans. While the tool worked without any advanced configuration for one of the fans (acpi address **1335**), the second fan's behavior was not affected. So, I found (with your other tool "afc-scout") that the acpi address of the 2nd fan is **1431**.
Thus, I made a modification to your bash script "asus-fan-control": Where the "set_acpi_temps" 
 function is called, I added a line to call it for a 2nd time passing as address "1431". As a result, whenever the asus-fan-control service runs, it affects both of the laptop's fans.
As a suggestion, it would be nice to support dual-fan laptops in the future. :)

**Comment by dominiksalvet** [comment]
Hello @AntonisKl and welcome to the asus-fan-control community! :wave: :smile: 

I am really happy that you enjoy using asus-fan-control and your post has made me even happier! :smile: This is the moment I was waiting for since developing [afc-scout](https://github.com/dominiksalvet/afc-scout). Finally, afc-scout has borne fruit! :rocket: :apple: That is very good news! :clap:

Thank you so much for your patience with the analysis of your device fans! This has brought the opportunity of adding **native support for dual-fan laptops**. I am definitely in and once I have time **I will implement it**! :rocket:

Unfortunately, I do not have time right now, so I will come back later and add support for your device as soon as possible. :timer_clock: It will most likely be done in two steps:

1. Add support for a single fan - very soon.
2. Add support for both fans - I do not know yet.

---

BTW, did you alter the output of `model-info` somehow (e.g., your modifications)? Since your model is classified as not `tested`, it should have displayed `temperatures 55 60 62 65 68 72 76 80`, which are the default temperatures used for any unrecognized device.

**Comment by AntonisKl** [comment]
Hello @dominiksalvet,
Happy to be in this community! 😁
To answer your question: Yes, I had altered the temperatures before running "sudo asus-fan-control get-temps".

**Comment by dominiksalvet** [comment]
> Hello @dominiksalvet,
> Happy to be in this community! 
> To answer your question: Yes, I had altered the temperatures before running `sudo asus-fan-control get-temps`.

That's right. But your `sudo asus-fan-control model-info` output should not be affected and should print what I have written in my previous post. That's a bit odd to me. 🤔

**Comment by dominiksalvet** [comment]
Still working on some details that need to fit in the upcoming release.

**Comment by AntonisKl** [comment]
> > Hello @dominiksalvet,
> > Happy to be in this community!
> > To answer your question: Yes, I had altered the temperatures before running `sudo asus-fan-control get-temps`.
> 
> That's right. But your `sudo asus-fan-control model-info` output should not be affected and should print what I have written in my previous post. That's a bit odd to me.

I realized that I have manually set the "FALLBACK_TEMPS" environmental variable to "45 50 55 60 65 70 75 80". So, the code works correctly.

**Comment by dominiksalvet** [comment]
All right, so your device should work with the [latest asus-fan-control](https://github.com/dominiksalvet/asus-fan-control/releases/tag/3.7.0) without any manual intervention. Use `sudo gitpack install github.com/dominiksalvet/asus-fan-control` to update.

---

**Thank you so much** for this contribution and especially for your analysis! :clap: The dual fan support has been added to asus-fan-control thanks to that. :heart: :rocket: Good job! :+1:

> I am closing this issue but should you have any problems or so, feel free to continue in the discussion. :smile:

**Comment by dominiksalvet** [comment]
Soon, I will also update [afc-scout](https://github.com/dominiksalvet/afc-scout) to reflect these changes.
