### ISSUE TITLE
Add support for ROG Strix SCAR II

### ISSUE THREAD

**Issue by shyrma** [dominiksalvet/asus-fan-control#4]
**Environment**
asus-fan-control version: 2.8.1
OS: Linux Mint 19.2 Cinnamon
Linux Kernel: 4.15.0-58-generic
Processor: Intel© Core™ i7-8750H CPU @ 2.20GHz × 6
Graphics: Intel Corporation Device 3e9b, Intel driver: i915 v: kernel 
		  GeForce RTX 2070/PCIe/SSE2 v: 4.6.0 NVIDIA 430.26n.

**Temperature configuration**
55 56 57 58 59 60 61 62

**Notebook model name**
Strix GL704GW_GL704GW

Hi dominiksalvet

First of all thanks a lot for development of this program!

Looks like asus-fan-control has no affect on my fans.
I have following output in console

```
yurii@yurii-laptop:$ sudo gitpack install github.com/dominiksalvet/asus-fan-control=master
[install] github.com/dominiksalvet/asus-fan-control d311ed4

yurii@yurii-laptop:$ sudo asus-fan-control -get-temps
55 56 57 58 59 60 61 62

yurii@yurii-laptop:$ sudo asus-fan-control -set-temps:'55 57 59 61 63 65 67 69'

yurii@yurii-laptop:$ sudo asus-fan-control -get-temps
55 56 57 58 59 60 61 62
```

As you may note applying -set-temps has no affect since -get-temps shows other (default) numbers. Also default numbers are not working as well, because (if I understand correctly) fans should be off when temperature is < 55, but I can totally hear fan noise even if temperature is < 50.

**Comment by dominiksalvet** [comment]
@shyrma Hi and thank you for your kind words! :heart: But unfortunately, it seems that I can't help you with that issue... :disappointed: 

The program should work even with untested models as long as they have the same ACPI addresses for the fan configuration, it only uses the default temperatures. In this particular case, it looks like ASUS has changed the addresses, or maybe there is a problem related to two-fan model if applicable. As you pointed out, it really looks like the program has zero effect on your machine. Since you are testing a new model, it is certainly better than unexpected shutdown or so...

For the sake of completeness, reboot your device and try to run the `sudo asus-fan-control` commands mentioned and print also their return values. You can do it by executing `echo "$?"` right after each command.

I am really sorry but I created this project for my own machine and the fact it works on other models was just coincidence, so I added only a basic mechanism to support multiple models. Now, I keep it maintaining only for purposes of [GitPack](https://github.com/dominiksalvet/gitpack) and in case that someone will find out that it works on its untested model without any work, in which case we would try to find the best temperature configuration and add it as an official tested model and the program will recognise it.

But if it does not work for your model at all, I can't help you. I would recommend you to try other projects for fan control. Alternatively, if you like this program so much, have a good knowledge of Unix shell (not Bash) and also have some time, you can add the support for your model yourself. I am open to help. :+1:

**Comment by shyrma** [comment]
thanks for information!

Of course I did reboot, there was no effect.
Since I'm not good in Unix shell, looks like I have to take a look on available alternative fan control apps ;-)

**Comment by dominiksalvet** [comment]
@shyrma I am really sorry that I can't help you. :cry:

You know what? If you will ever work with Unix Shell or any interpreted language and you will need to solve installation, updating and uninstallation of your program by end users, take a look at [GitPack](https://github.com/dominiksalvet/gitpack). It is as simplest as it can be and we can cross our paths once again. Wish you the best! :smile:

**Comment by shyrma** [comment]
Ok, I'll take your advise into account ;-)

**Comment by dominiksalvet** [comment]
If anyone is interested in **adding support for this model**, take a look at [this post](https://github.com/daringer/asus-fan/issues/44#issuecomment-307589414). It might be helpful as all current supported models are based on it.

**Comment by dominiksalvet** [comment]
I am opening this issue to let other people know that it is not resolved yet and so they can contribute.

**Comment by dominiksalvet** [comment]
Hello @shyrma!

I have recently released the [3.0.0](https://github.com/dominiksalvet/asus-fan-control/releases/tag/3.0.0) version, which supports different ACPI fan base addresses among tested models. It means that if you know or find the base ACPI address for your model, asus-fan-control will be able to fully support it.

I do not imagine that you know the ACPI base address but just in case. There is hope! :rocket:

**Comment by dominiksalvet** [comment]
@shyrma Hopefully the last spam of this kind... But I have good news!

Please have a look at [this comment](https://github.com/dominiksalvet/asus-fan-control/issues/6#issuecomment-590110254). Maybe it can help! :smiley:

**Comment by quancore** [comment]
it is the same, not working.
