### ISSUE TITLE
Add support for Asus TUF FX504

### ISSUE THREAD

**Issue by vivekvjnk** [dominiksalvet/asus-fan-control#47]
**Environment**
State asus-fan-control version and OS information.

**Basic configuration**
If only temperatures were configured, add output of:
* `sudo asus-fan-control get-temps`
* `sudo asus-fan-control model-info`

**Advanced configuration**
If advanced configuration was used, add output of:
* `sudo FALLBACK_ADDRS='<addrs>' FALLBACK_TEMPS='<temps>' asus-fan-control model-info`

**Additional context**
Add any additional context.

**Comment by dominiksalvet** [comment]
Hello @vivekvjnk and welcome to the asus-fan-control community! :wave:

Unfortunately, it is not that easy... :confused: I have modified your original post so that it includes prepared items to be filled in based on your configuration. Please, take a look at [contributing.md](https://github.com/dominiksalvet/asus-fan-control/blob/master/contributing.md) file as well. I am trying to keep it as simple as possible to prevent these situations. :rocket: 


please fill the missing stuff of your post, which I have modified... A this information are required.

**Comment by dominiksalvet** [comment]
Hello @vivekvjnk, any news on that? Have you managed to make asus-fan-control work on your device? Do you use an alternative tool that works for you (if so, tell us which one)? Please let us know. :wink: 

---

BTW does this issue relate to #72? Is your laptop FX504GE, or just FX504? (if you still have it of course :smile:)

**Comment by dominiksalvet** [comment]
Closing as being ignored very well. :smile: :upside_down_face:
