### ISSUE TITLE
file /proc/acpi/call does not exist

### ISSUE THREAD

**Issue by arthas168** [dominiksalvet/asus-fan-control#62]
Hello, Dominik! First off - kudos to you for this awesome project, I live in a very hot and damp region but also quite often have to work early mornings while my gf is sleeping in the same room. Now, that wouldn't be a problem if the fans weren't blasting like a space shuttle. Tried to look for a way to lower fan speed in BIOS - no luck. Story short - you're a real life saver! There's just a small issue that I'm not even sure is a bug :beetle: ,  but still wanted to take note.

Model: Asus rog strix g531gt

I'm using a newly installed Manjaro and trying to use afc, both terminal and gui. But when I try to adjust the temp using either of them, I get `file /proc/acpi/call does not exist` :( 

On a side note: although it does _seem_ to be working (fans are not as noisy), after a few seconds or minutes (or when I start doing something more intense) they start blasting again and I have to run the command once more.

On another side note: how do I completely stop the program, so that the laptop can act like a rocket again, when it won't bother anyone? :sweat_smile:

**Comment by dominiksalvet** [comment]
Hello @arthas168! :wave:

In your particular case, I think it is connected with https://github.com/dominiksalvet/gitpack/issues/7, so let's resolve this one first. :rocket: 

> On a side note: although it does _seem_ to be working (fans are not as noisy)

Very interesting, it shouldn't do a thing without the ACPI call... :smiley: 

> On another side note: how do I completely stop the program, so that the laptop can act like a rocket again, when it won't bother anyone?

Uninstall asus-fan-control... why? It is not a daemon, it is not running. It is a one-shot action that is run on particular events such as boot and wake-up from sleep to imitate the permanent effect. The rest work is done behind the ACPI wall... :smile: 

BTW, you can always adjust temperatures so that they match the original ones using `asus-fan-control set-temps <temps>`...

**Comment by arthas168** [comment]
Hi again, sorry for the late response, for some reason I didn't receive a notification :sweat_smile: 

On the second note - noted :heavy_check_mark: , makes sense!

Alright, will continue the discussion in that other thread, thanks again for helping out!

**Comment by dominiksalvet** [comment]
Hello @arthas168, have you managed to make asus-fan-control work on your device? :thinking:

**Comment by dominiksalvet** [comment]
bump

**Comment by cives** [comment]
Hi, I am having this same issue on a Manjaro Plasma installation on an Asus Tufgamer laptop.
I didn't install using Gitpack, but with yay. In recent times I had it installed and it helped to keep the unbereable permanent noise under control, but I reinstalled the system and although I kept apart my home partition, it seems that afc didn't remain as configured before. Acpi seems to be installed, but yet there is that message and afc does not start.
Any ideas, please?
And thank you, Dominik, for this wonderful piece of work.
Antonio

**Comment by dominiksalvet** [comment]
> Hi, I am having this same issue on a Manjaro Plasma installation on an Asus Tufgamer laptop.
> I didn't install using Gitpack, but with yay. In recent times I had it installed and it helped to keep the unbereable permanent noise under control, but I reinstalled the system and although I kept apart my home partition, it seems that afc didn't remain as configured before. Acpi seems to be installed, but yet there is that message and afc does not start.
> Any ideas, please?
> And thank you, Dominik, for this wonderful piece of work.
> Antonio

Hello Antonio! :wave:

First, let me say that I am not an Arch user, neither a user of its forks (such as Manjaro), so I have zero experience with `yay` and similar. But the error message is clear. The ACPI entry point `/proc/acpi/call` (file), which is used by AFC to perform ACPI calls, does not exist.

Let us consider that `acpi_call` is installed correctly on your system. You also need to load the ACPI kernel module. You can do it running `modprobe acpi_call` (run with root permissions). Then, you can try AFC again.

---

Personally, I would rather try the following solution.

1. Uninstall AFC.
2. Make sure that `acpi_call` module is installed.
3. Install GitPack.
4. Install AFC using GitPack.

It will ensure that `acpi_call` is loaded on boot before AFC, so that everything works. The AUR installation is out of my scope but if you insist on that method, we can ping the AFC AUR maintainer... :rocket:

**Comment by cives** [comment]
Thank you very much, Dominik,
I will try and will keep you posted.
Regards,
Antonio
