### ISSUE TITLE
ASUS TUF FX505DY - issues with install ?

### ISSUE THREAD

**Issue by Opalie** [dominiksalvet/asus-fan-control#65]
#35 related:
I own a ASUS TUF FX505DY, installed everything recently and got annoyed by the fans. But I can't seem to install or make work anything...
gitpack is installed. Here are the things I tried to check if anything worked:
```

$ gitpack status asus-fan-control
fatal: unable to access 'https://asus-fan-control.git/': Could not resolve host: asus-fan-control.git
<ERROR> status asus-fan-control
```
`
zola@zola-asus:~$ sudo asus-fan-control set-temps 45 50 55 60 65 70 75 80`
No response.

I uninstalled and reinstalled it.

```
zola@zola-asus:~$ sudo gitpack uninstall github.com/dominiksalvet/asus-fan-control
[uninstall] github.com/dominiksalvet/asus-fan-control 3.8.0
zola@zola-asus:~$ sudo gitpack install github.com/dominiksalvet/asus-fan-control
[install] github.com/dominiksalvet/asus-fan-control 3.8.0
```

```
zola@zola-asus:~$ gitpack status asus-fan-control
fatal: unable to access 'https://asus-fan-control.git/': Could not resolve host: asus-fan-control.git
<ERROR> status asus-fan-control
```
Tried afc-scout:
```
zola@zola-asus:~$ sudo afc-scout 1334 1343
/usr/local/bin/afc-scout: 48: Illegal number: Erro
```
Are all of these normal outputs? 
edit: extremely sorry, I forgot to set a title...

**Comment by dominiksalvet** [comment]
Hello @Opalie and welcome to the asus-fan-control community! :wave:

> Are all of these normal outputs?

> ```
> zola@zola-asus:~$ gitpack status asus-fan-control
> fatal: unable to access 'https://asus-fan-control.git/': Could not resolve host: asus-fan-control.git
> <ERROR> status asus-fan-control
> ```

Yes, this output is expected. You are talking to GitPack and GitPack always expects the project's URL. So use `sudo gitpack status github.com/dominiksalvet/asus-fan-control`. `sudo` is used because you want to access the global database, otherwise, the local one (per-user) would be used... and asus-fan-control is installed globally... Do not be afraid to use the TAB key to show hints, especially for URLs.

---

About the other issues... Please update asus-fan-control and afc-scout to the latest version (I have made some relevant changes to both). Simply use `sudo gitpack install github.com/dominiksalvet/asus-fan-control github.com/dominiksalvet/afc-scout` and GitPack will do the rest. Then try it all again and report the output (probably there will be an error, but we will have its precise description).

**Comment by Opalie** [comment]
`$ sudo gitpack install github.com/dominiksalvet/asus-fan-control
acpi call failed with 'Error: AE_NOT_FOUND'
failed to apply changes immediately
[update] github.com/dominiksalvet/asus-fan-control 3.8.1 <- 3.8.0
`
Thank you a lot for all these informations, seems like it updated and only needs me to restart? Do you still want me to retry the previous input after a restart? (it will only be possible later today, as I am working all day.)

**Comment by dominiksalvet** [comment]
Sorry but it looks like a dead end for your model. See the AE_NOT_FOUND label in the asus-fan-control issues... It has not been solved yet and it also seems that it will not ever be (for afc).

Should you find an alternative that will work for you, certainly let us know. I like to connect the ASUS community. 😊

**Comment by dominiksalvet** [comment]
Hello @Opalie. It has been some time but I have realized that there is a possible alternative fan tool that might work on your device. Have a look at #56. :smile: Please let me know whether it works, or if you are using another solution... :rocket:

**Comment by dominiksalvet** [comment]
I have also come by https://github.com/leonmaxx/asus_fanmode... It would be great to try whether it works. 😉
