### ISSUE TITLE
file /proc/acpi/call does not exist on kernel 5.4.0-56-generic

### ISSUE THREAD

**Issue by vaibhav-hexa** [dominiksalvet/asus-fan-control#68]
Hello @dominiksalvet ,
Thank you for your great work on the asus fan control. It made linux useable for me, by turning down all that fan noise. :+1: 

**Environment**
asus-fan-control 3.9.0
Linux Mint 20 Cinnamon 4.6.7
Asus Vivobook X507UF (i5-8250U)

**Description**
asus-fan-control no longer works after update to kernel via mainstream. 
The error message is: `/proc/acpi/call does not exist` on kernel 5.4.0-56-generic.

**Replication**
Update to kernel 5.4.0-56-generic and this issue should occur.

**Comment by dominiksalvet** [comment]
Hello @vaibhav-hexa! :wave:

Let's start with some questions. Have you read #42, #60, and #62? Did you try the proposed solutions in those issues?

**Comment by vaibhav-hexa** [comment]
> Hello @vaibhav-hexa! 
> 
> Let's start with some questions. Have you read #42, #60, and #62? Did you try the proposed solutions in those issues?

Hi @dominiksalvet ,
Yes, I had tried those steps before, and they would work fine earlier. But now when I re-install `acpi-call-dkms` , the secure boot configuration comes up which I am trying to avoid. Previously, it was possible to bypass secure boot but not with the latest kernel. (Sorry, I didn't mention this in 1st post).

**Comment by dominiksalvet** [comment]
Okay, thank you for the additional info! :smile: If you encounter those issues during the `acpi-call-dkms` APT package installation (which GitPack invokes automatically), then there is probably no other solution than turning the secure boot off in BIOS (or downgrading the kernel).

I had had a similar issue with a kernel module, something like `modprobe: ERROR: could not insert 'xxx': Operation not permitted` (have you seen it as well?), and from time to time, it appeared. I have ultimately solved it by turning the secure boot off since I need to work with unsigned kernel modules. Obviously, the secure boot does not like unsigned drivers... :slightly_smiling_face:

Anyway, as far as I know, you should be able to turn off the secure boot in BIOS between reboots without doing any harm (unless you are leveraging multi-boot with Windows for example, if that is even possible with secure boot).

**Comment by vaibhav-hexa** [comment]
> I had had a similar issue with a kernel module, something like `modprobe: ERROR: could not insert 'xxx': Operation not permitted` (have you seen it as well?)

Yes, I have the same error now. Thank you for the hints, I will recheck by turning off the secure boot. Alternatively, I will downgrade to previous kernel version, where fan-control worked fine. :)

**Comment by dominiksalvet** [comment]
> I will recheck by turning off the secure boot.

Okay, if you do so, please let us know whether it helped. :+1:

**Comment by vaibhav-hexa** [comment]
> > I will recheck by turning off the secure boot.
> 
> Okay, if you do so, please let us know whether it helped.

Yes, it worked! :) Only disabling secure boot is enough, no need to reinstall any packages!

**Comment by dominiksalvet** [comment]
Glad to hear that! 😊👏

**Comment by dominiksalvet** [comment]
@vaibhav-hexa One last thing. I have noticed that you use an untested device (Asus Vivobook X507UF) and judging from your comments, it works for you. Please consider giving something back to the asus-fan-control community and create an issue to add your device into the official asus-fan-control tested devices list stated in the readme.

It is that simple – https://github.com/dominiksalvet/asus-fan-control/blob/master/contributing.md. Please do it as soon as possible since many similar issues (working untested device) did not lead to a contribution at the end of the day. (see [looking for tester](https://github.com/dominiksalvet/asus-fan-control/issues?q=is%3Aissue+is%3Aopen+label%3A%22looking+for+tester%22) label)

You, the testers, are the ones who make asus-fan-control awesome! :smile: :rocket: (convince yourself – [time machine](https://github.com/dominiksalvet/asus-fan-control/tree/1.0.0), [ultra time machine](https://github.com/dominiksalvet/asus-zenbook-ux430ua-linux-setup))

**Comment by vaibhav-hexa** [comment]
> @vaibhav-hexa One last thing. I have noticed that you use an untested device (Asus Vivobook X507UF) and judging from your comments, it works for you. Please consider giving something back to the asus-fan-control community and create an issue to add your device into the official asus-fan-control tested devices list stated in the readme.

Happy to update the device tree :). I have created a new issue #73 [Add X507UF](https://github.com/dominiksalvet/asus-fan-control/issues/73). I shall go ahead with forking the branch and push the changes.
