### ISSUE TITLE
Error Asus TUF FX504GE

### ISSUE THREAD

**Issue by desekilibrio** [dominiksalvet/asus-fan-control#72]
hi i get an error every time i try to start both afc-scout and asus-fan-control in my asus TUF FX504GE. 

The asus fan control error is:

/ usr / local / bin / asus-fan-control: 411: Illegal number: Erro

the error in afc-scout is similar:

------ base address 1335 ------
/ usr / local / bin / afc-scout: 48: Illegal number: Erro

Could you tell me what the problem is?

**Comment by dominiksalvet** [comment]
Hi @desekilibrio, it has been quite a while since the last activity on this issue but I have transferred it here to asus-fan-control since it can be grouped with other AE_NOT_FOUND issues (which is what your problem looks like). Please, can you try the latest version of asus-fan-control again to make sure it is the AE_NOT_FOUND issue? Asus-fan-control now prints full names of ACPI errors... :+1: 

In case you are already using another fan solution, please leave us a link. You may help the ASUS community. :rocket: :smile: Thank you for your time! :heart_eyes:

**Comment by dominiksalvet** [comment]
Closing as this issue gets older... If you have something to add, feel free to do so. :rocket:
