### ISSUE TITLE
Add support for Asus K53SC

### ISSUE THREAD

**Issue by lucamarini22** [dominiksalvet/asus-fan-control#81]
**Environment**
asus-fan-control version: asus-fan-control 3.9.0
OS: Arch Linux

**Basic configuration**
If only temperatures were set and they worked, add output of:
* `sudo asus-fan-control get-temps` output: 40 45 50 55 59 63 65 67 
* `sudo asus-fan-control model-info`: 
  ```
  name K53SC
  addresses 1335
  default-temps 55 60 62 65 68 72 76 80
  tested false
  ```

**It does not work**
- asus-fan-control does not work on my device:  my fan is always at maximum speed
- I executed `sudo asus-fan-control set-temps 30 35 40 45 50 55 60 65 ` and `sudo asus-fan-control set-temps 60 65 70 75 80 85 90 95` but the fan speed didn't change at all, and hen I execute `sudo asus-fan-control get-temps` I get the setted temperatures.

As said in #78 , I uninstalled asus-fan-control, rebooted, executed afc-scout and  I got this output:
```
------- base address 1335 ------
[1334] = 0
[1335] = 40 <- possible start
[1336] = 47
[1337] = 55
[1338] = 62
[1339] = 72
[1340] = 80
[1341] = 85
[1342] = 90 <- possible end
[1343] = 95
------ base address 1431 ------
[1430] = 44
[1431] = 80 <- possible start
[1432] = 84
[1433] = 89
[1434] = 94
[1435] = 94
[1436] = 94
[1437] = 94
[1438] = 94 <- possible end
[1439] = 98
```

and here you can find the output of afc-scout 0 4095:

[output_of_afc_scout_0_4095.txt](https://github.com/dominiksalvet/asus-fan-control/files/5759047/output_of_afc_scout_0_4095.txt)

**Additional context**
- the output of command `sensors` doesn't detect any fan sensors, its output is the following:
```
asus-isa-0000
Adapter: ISA adapter
temp1:        +55.0°C  
BAT0-acpi-0
Adapter: ACPI interface
in0:           3.62 V  
curr1:         0.00 A  
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +55.0°C  (high = +86.0°C, crit = +100.0°C)
Core 0:        +45.0°C  (high = +86.0°C, crit = +100.0°C)
Core 1:        +45.0°C  (high = +86.0°C, crit = +100.0°C)
Core 2:        +46.0°C  (high = +86.0°C, crit = +100.0°C)
Core 3:        +45.0°C  (high = +86.0°C, crit = +100.0°C)
acpitz-acpi-0
Adapter: ACPI interface
temp1:        +55.0°C  (crit = +103.0°C)
```

- and here is the output of `sudo pwmconfig`:
```
# pwmconfig version 3.6.0
This program will search your sensors for pulse width modulation (pwm)
controls, and test each one to see if it controls a fan on
your motherboard. Note that many motherboards do not have pwm
circuitry installed, even if your sensor chip supports pwm.

We will attempt to briefly stop each fan using the pwm controls.
The program will attempt to restore each fan to full speed
after testing. However, it is ** very important ** that you
physically verify that the fans have been to full speed
after the program has completed.

/usr/bin/pwmconfig: There are no pwm-capable sensor modules installed
```

**Comment by dominiksalvet** [comment]
Hello @lucamarini22! :wave:

I've been thinking about this for a while and once again I want to state that it seems very similar to #76. If it is not working out of the box (with the default ACPI address range), you may want to tinker around with custom ACPI addresses based on values that seem like temperatures sequence of your `afc-scout 0 4095` dump. But it may be dangerous since you would be overwriting some ACPI values of which we do not know the purpose. Unfortunately, this is the only solution that comes to my mind now and I would thoroughly consider its consequences.

If you decide to go this way, I would strongly recommend to perform only one change of custom ACPI address range modification per boot. I.e., change custom addresses, wait if there is any fan speed effect, and reboot if not. And again with different addresses. This way, you may found new tipping point of temperatures address, which may bring support for new devices including yours. AFC is prepared for that – once one does that and the device support is added to AFC, AFC may be used normally on the device. Until then, you have to use the `FALLBACK_ADDRS` and `FALLBACK_TEMPS` environment variables for each `asus-fan-control` command. E.g., to set custom temperatures with a custom base address:

```
sudo FALLBACK_ADDRS='<custom-base-address>' FALLBACK_TEMPS='<custom-temperatures>' asus-fan-control set-temps default
```

Based on your `model-info`, the explicit behavior of `asus-fan-control ...` commands on your device, would be:

```
FALLBACK_ADDRS='1335' FALLBACK_TEMPS='55 60 62 65 68 72 76 80' asus-fan-control ...
```

**Comment by dominiksalvet** [comment]
When device is not tested in AFC, it needs to figure out, which values (address and temperatures) to use by default. If no `FALLBACK_*` variable provided, it uses the default values of the UX430UA device. However, using `FALLBACK_*` variables allows us to use whichever address and temperatures we want, which is good for new, untested, devices.

**Comment by dominiksalvet** [comment]
Hello @lucamarini22, any updates on this? :thinking:

**Comment by lucamarini22** [comment]
No @dominiksalvet, I'm sorry but I have no updates for the moment

**Comment by dominiksalvet** [comment]
Okay, so I will close this issue. Let me know if you find out something, though. :rocket:
