### ISSUE TITLE
Partially unfunctional on GL553VE

### ISSUE THREAD

**Issue by Bounty780** [dominiksalvet/asus-fan-control#98]
**Environment**

asus-fan-control 3.11.0
Endeavour OS, x86-64

**Description**

When asus-fan-control is functional (for example, with all temperatures of 35 for ease of replication), fans wind up erratically. For example, when a certain application is opened, that triggers the videocard, the fans wind up. Fans may also wind up during idle periods, for no particular reason.

**Replication**

1. Start asus-fan-control
2. Set temperatures to 35
3. Open applications and work like usual

**Additional context**

There is a possibility that there are differences inter-revision, as during my run of afc-scout, address 1430's value was 0, while  @arruor's value turned out to be 12.

**Comment by dominiksalvet** [comment]
Hello! :wave:

> There is a possibility that there are differences inter-revision, as during my run of afc-scout, address 1430's value was 0, while @arruor's value turned out to be 12.

The value of the address 1430 is irrelevant for this model since it should have only one fan (base address 1335). For more info, see https://github.com/dominiksalvet/asus-fan-control/blob/master/src/data/models#L11.

> When asus-fan-control is functional (for example, with all temperatures of 35 for ease of replication), fans wind up erratically. For example, when a certain application is opened, that triggers the videocard, the fans wind up. Fans may also wind up during idle periods, for no particular reason.

I tend to think that you do not know how AFC works. Please, see https://github.com/dominiksalvet/asus-fan-control#custom-temperatures. Then, run `sudo asus-fan-control set-temps default` and try if the fan works better.

Also, please add the output of `sudo asus-fan-control model-info`.

**Comment by Bounty780** [comment]
> Then, run `sudo asus-fan-control set-temps default` and try if the fan works better.

The fan speed didn't change.

> Also, please add the output of `sudo asus-fan-control model-info`.
```
name GL553VE
addresses 1335
default-temps 45 50 55 60 65 70 75 80
tested true
```

**Comment by dominiksalvet** [comment]
Then I am sorry but I cannot help you since I am not an expert on ACPI stuff. I just know how to write code in POSIX shell... Maybe @arruor or AFC community may have some insight.

BTW your OS may also play a role in this. If you have an opportunity to try AFC on a fresh new OS (Ubuntu, ideally), it would be great.
